import { UserRole } from "@/lib/definitions";
import { PhoneNumberFormat } from "@/lib/sinitizePhone";

export type TInputsEmployee = {
  name: string;
  lastName: string;
  phonePersonal: string | null;
  emailPersonal: string | null;
  idCheck: number | null;
  passwordCheck: string | null;
  entryOffice: string | null;
  entrySaturdayOffice: string | null;
  exitOffice: string | null;
  exitSaturdayOffice: string | null;
  entryLunch: string | null;
  exitLunch: string | null;
  idDepartment: number | null;
  idPosition: number | null;
  branch: number | null;
  gender: "MASCULINO" | "FEMENINO";
  status: 1 | 2 | 3;
  phoneCompany: string;
  phoneExtCompany: number | 0;
  address: {
    street: string;
    numberIn: string;
    numberOut: string;
    state: string;
    country: string;
    municipality: string;
    zipCode: string;
    neighborhood: string;
  };
  emailCompany: string;
  scheduleDescription: string;
  policies: string;
  group: string;
  homePhone: string;
  sons: number | 0;
  daughters: number | 0;
  birthDate: string;
  nationality: string;
  socialSecurityNumber: string;
  rfc: string;
  curp: string;
  weight: string;
  height: string;
  bloodType: string;
  constitution: string;
  healthStatus: string;
  education: string;
  skills: string;
  comments: string;
  emergencyContacts: {
    name: string;
    kinship: string;
    phone: PhoneNumberFormat;
  }[];
  keyAspelNOI: string;
  keyCONTPAQi: string;
  admissionDate: string;
  anniversaryLetter: string;
  visibleRecords: boolean;
  dischargeDate: string;
  dischargeReason: string;
  role: UserRole[];
};
